# -*- coding: utf-8 -*-
"""Lab_3_Loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x2axk06ESpc0KncUt9kqYkIjTEHxc-lC

# Loops

for loop

while loop

break

continue
"""

numbers = [1,2,3,4,5,6,7,8,9,10]

numbers

numbers[2]**2

for i in numbers:
    print(i**2)

numbers = [1,2,3,4,5,6,7,8,9,10]

for number in numbers:
    if number%2 == 0:
        print(number**2)
    else:
        print("{} is an odd number".format(number))



# for loop
books=['Matthew','Mark','Luke','John','Acts']

for book in books:
    print(book)

for x in range(1,11):
    print(x)



a =range(3)

a

range(0,10)

for i in range(10):
    print('Hello!')



# Another for loop
gospel=['Matthew','Mark','Acts','Luke','John','Hebrews','Romans']

for book in gospel:
    if book == 'Acts':
        print(f'{book} is not part of the gospels')
        
    elif book == 'Hebrews':
        print(f'{book} is not part of the gospels')
        
    elif book == 'Romans':
        print(f'{book} is not part of the gospels')
            
            
    else:
        print(book)

# Another for loop
gospel=['Matthew','Mark','Luke','John','Acts']

for book in gospel:
    print(book.upper())

numbers = [23,34,56,7,3,5,89,90,876,567,45,324,67,8,8,9,45,3,9,11,25,65,82,76,73]

len(numbers)

for number in numbers:
    if number>70:
        print(number)

"""Write a for loop that iterates over the names list to create a usernames list. 

To create a username for each name, make everything lowercase and replace spaces with underscores. 

"""

names = ["Joe Mettle", "Monica Acheampong", "Chandler Wimbe", "Lady Phoebe", "Knii Amponsah","Bernard Boakye Yiadom","Henry Ayitey"]

names[0]
names[1]
names[2]

names

names[1].lower().replace(' ','_')

for i in names:
    names[i].lower().replace(' ','_')



names[0] = names[0].lower().replace(' ','_')

names

len(names)

for i in range(len(names)):
    print(i)

names[6]

usernames = []

usernames.append('Jessica')

usernames

0,1,........6

# solution
usernames = []

for i in range(len(names)):
    
    a = names[i].lower().replace(' ','_')
    
    usernames.append(a)
    
print(usernames)

# modifying the list instead

names = ["Joey Tribbiani", "Monica Geller", "Chandler Bing", "Phoebe Buffay"]

for name in names:
    name = name.lower().replace(' ','_')
    print(name)

names

"""### Counting"""

tokens = ['<greeting>', 'Hello World!','<colour','</greeting>','<strong>','Bold','</strong>']

count = 0

for token in tokens:
    if token[0] == '<' and token[-1] == '>':
        count += 1
print(count)



"""##### Count the names with 6 letters in the list called students

students = ["Joe", "Mettle", "Monica","Acheampong", "Chandler","Wimbe", "Lady","Phoebe", "Afrakoma","Amponsah"]
"""

students = ["Joe", "Mettle", "Monica","Acheampong", "Chandler","Wimbe", "Lady","Phoebe", "Afrakoma","Amponsah"]

count = 0
for student in students:
    if len(student) == 6:
        count+=1
print(count)

"""### Building Dictionaries using the for loop and the get method"""

book_title =  ['great', 'expectations','the', 'adventures', 'of', 'sherlock','holmes','the','great','gasby','hamlet','adventures','of','huckleberry','fin']

# Task
# Build a dictionary containing the words in the list and the number of times each appeared in the list.
# Alternatively , count the number times each word appeas in the list.

### solution 1 (using the for loop)

word_count = {}

for word in book_title:
    if word not in word_count:
        word_count[word] = 1
    else:
        word_count[word] += 1
print(word_count)

score = {'Joejoe':12,'Ama':10,'Adam':15}

word_count['great'] = 1

score['Dominic'] += 1

score

#solution2 (using the get method)

print()
print('Using the get method:')

No_of_words = {}
for word in book_title:
    No_of_words[word] = No_of_words.get(word,0)+1
print(No_of_words)

score = {'Joejoe':12,'Ama':10,'Adam':15}

score['Domenic']

print(score.get('Dominic',100))

score



word_count.values()

list(word_count.keys())

"""## while loop (infinite loop)"""

#while 1<2:
    #print('Kelden')





marks = 15

while marks > 10:
    print("Hurray!!!!")
    marks-=1

a = 0
while a<10:
    print(a**2)
    a+=1











"""## break and continue"""

# Break
# Break ends the loop at a specified point
New_testament=['Matthew','Mark','Luke','John','Acts','Romans','1st Chorinthians']
for book in New_testament:
    gospel = []
    if book == 'John':
        #print(f'{book} Hei!, John is the last gospel')
        break
    else:
        gospel.append(book)
        print(gospel)

for i in range(1,10):
    if i == 6:
        print('we are on the sixth square.')
        break
    
    else:
        print(i**2)

for i in range(1,10):
    if i == 6:
        print('we are on the sixth square...skipping')
        continue
    
    else:
        print(i**2)

# Task: write a programme(codes) that will load poducts into a 100tonks capacity ship. 
# The ship cannot take load beyond its capacity.



# Solution

agri_products = [("bananas", 15), ("maize", 24), ("beans", 42), ("yam", 120), ("plantain", 5),("pepper",10)]

weight = 0
items = []
for product, product_weight in agri_products:
    print("current weight: {}".format(weight))
    if weight >= 100:
        print("  breaking from the loop now!")
        break
    elif weight + product_weight > 100:
        print("  skipping {} ({})".format( product, product_weight))
        continue
    else:
        print("  adding {} ({})".format( product, product_weight))
        items.append(product)
        weight += product_weight

print("\nFinal Weight: {}".format(weight))
print("Final Items: {}".format(items))

for item, item_weight in agri_products:
    print(item)
    print(item_weight)



